// provider/src/components/Button.jsx
import React, { useState, useEffect } from "react";
import store from "consumer/sharedStore";

const Button = () => {
  const [count, setCount] = useState(store.getState().count);

  useEffect(() => {
    const unsubscribe = store.subscribe((newState) => {
      setCount(newState.count);
    });
    return () => unsubscribe();
  }, []);

  const handleClick = () => {
    store.getState().increment();
  };

  return (
    <button onClick={handleClick}>
      Provider Increment {count}
    </button>
  );
};

export default Button;

// vue-provider/src/components/Button.vue
<template>
  
  <button @click="handleClick">{{ label }}</button>
</template>

<script>
import store from "consumer/sharedStore";
export default {
  name: 'Button',
  props: {
    label: {
      type: String,
      default: 'Click Me'
    }
  },
  methods: {
    handleClick() {
      this.$emit('click');
      store.getState().increment();
    }
  }
}
</script>

<style scoped>
button {
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
}
</style>
